name: social_media_app
description: A modern social media application with advanced theming and localization.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 
  riverpod_annotation: 
  go_router: 
  intl: ^0.19.0
  shared_preferences: 
  cached_network_image: 
  media_kit:     
  media_kit_video:          
  media_kit_libs_android_video:  
  media_kit_libs_windows_video:  
  http: 
  file_picker: 
  path_provider: 
  fab_circular_menu_plus: 
  package_info_plus: 
  url_launcher:
  google_fonts: 
  flutter_hooks: 
  image_picker:
  gap:
  iconify_flutter_plus:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  build_runner: 
  riverpod_generator: 

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
